### ISSUE TITLE
Demo page replacement

### ISSUE THREAD

**Issue by larvanitis** [dcorb/debounce-throttle#3]
First of all, I'd like to thank you for this precious resource!

Now, since the original blog post is down, could you enable Github pages for this repo?

For the people reading this: for now, you can view the example [index.html online](https://htmlpreview.github.io/?https://github.com/dcorb/debounce-throttle/blob/master/index.html) or the [archived blog post](https://web.archive.org/web/20180413042203/http://drupalmotion.com/article/debounce-and-throttle-visual-explanation), which contains more information.

**Comment by dcorb** [comment]
Hi, thanks!, you can read an improved version of this blog post and tool in css-tricks 
https://css-tricks.com/debouncing-throttling-explained-examples/

I will add anyway this info 👍
